name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check for changeset
        run: pnpm changeset status --since=origin/${{ github.base_ref }}

      - name: Build packages
        run: pnpm run build

      - name: Run tests
        run: pnpm test

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint
