name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check for changeset
        run: pnpm check-changeset

      - name: Build packages
        run: pnpm run build

      - name: Run tests
        run: pnpm test

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint
